# Generated by Django 2.0.7 on 2018-07-12 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180711_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='hash',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
