# Generated by Django 2.0.7 on 2018-07-12 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180712_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='type',
            field=models.CharField(default='register', max_length=30),
        ),
        migrations.AlterField(
            model_name='invitedusers',
            name='invited_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL),
        ),
    ]
